const profile = {
    name: "유영한",
    email: "gentry_@naver.com",
    tel: "010-9201-1597",
};

export { profile };

const portfolio = [
    {
        id: 1,
        title: "MEGABOX",
        type: "Single Page Application",
        font: ["Noto Sans KR"],
        color: ["#f5c518", "#c8c8c8", "#5fafff"],
        skill: ["React", "HTML5", "CSS3"],
        date: ["22.10.10 ~ 2022.10.20"],
        mock: process.env.PUBLIC_URL + "/mockup.png",
        cell: process.env.PUBLIC_URL + "/cellphone.png",
        link: "https://youngentry.github.io/megabox-react/",
        gitgub_link: "https://github.com/youngentry/megabox-react",
    },
    {
        id: 2,
        title: "2K",
        type: "Responsive Web",
        font: ["Noto Sans KR", "Oswald"],
        color: ["#e61f27", "#111", "#fff"],
        skill: ["jquery", "HTML5", "CSS3"],
        srcRes: process.env.PUBLIC_URL + "/2k_res.png",
        date: ["22.07.20 ~ 2022.07.28"],
        mock: process.env.PUBLIC_URL + "/mockup.png",
        cell: process.env.PUBLIC_URL + "/cellphone.png",
        link: "http://youngentry.github.io/2k-web-coding-220718",
        gitgub_link: "https://github.com/youngentry/2k-web-coding-220718",
    },
    {
        id: 3,
        title: "IMDB",
        type: "Standard Web",
        font: ["Noto Sans KR"],
        color: ["#f5c518", "#c8c8c8", "#5fafff"],
        skill: ["React", "HTML5", "CSS3"],
        date: ["22.08.29 ~ 2022.09.02"],
        mock: process.env.PUBLIC_URL + "/mockup.png",
        cell: process.env.PUBLIC_URL + "/cellphone.png",
        link: "https://youngentry.github.io/imdb-react/",
        gitgub_link: "https://github.com/youngentry/imdb-react",
    },

    {
        id: 4,
        title: "OPS",
        type: "Responsive Web",
        font: ["Noto Sans KR", "Gowun Batang"],
        color: ["#000", "#585858", "#fff"],
        skill: ["Jquery", "HTML5", "CSS3"],
        srcRes: process.env.PUBLIC_URL + "/ops_res.png",
        date: ["22.08.11 ~ 2022.08.15"],
        mock: process.env.PUBLIC_URL + "/mockup.png",
        cell: process.env.PUBLIC_URL + "/cellphone.png",
        link: "http://youngentry.github.io/ops",
        gitgub_link: "https://github.com/youngentry/ops",
    },
    {
        id: 5,
        title: "BESPOKE",
        type: "Standard Web",
        font: ["Noto Sans KR"],
        color: ["#d97e59", "#000", "#fff"],
        skill: ["JavaScript", "HTML5", "CSS3"],
        date: ["22.08.22 ~ 2022.08.26"],
        mock: process.env.PUBLIC_URL + "/mockup.png",
        cell: process.env.PUBLIC_URL + "/cellphone.png",
        link: "http://youngentry.github.io/bespoke",
        gitgub_link: "https://github.com/youngentry/bespoke",
    },
];

export { portfolio };
